version: '3.8'

services:
  mysql_db:
    container_name: "${DATABASE_CONTAINER}"
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - "./mysql_db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
